# Generated by Django 4.2.2 on 2023-07-02 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuta_name', models.CharField(default=None, max_length=15, verbose_name='Назва')),
                ('valuta_short', models.CharField(default=None, max_length=5, verbose_name='Скорочено')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(auto_now_add=True, verbose_name='Дата курсу')),
                ('rate_value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс')),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuta_rates', to='cashes.valuta', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Сума')),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuta_cash', to='cashes.valuta', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Каса підприємства',
                'verbose_name_plural': 'Каси підприємства',
            },
        ),
    ]
