# Generated by Django 4.2.3 on 2024-02-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='cash_name',
            field=models.CharField(default=None, max_length=30, verbose_name='Назва каси'),
        ),
    ]
