# Generated by Django 4.2.2 on 2023-07-07 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashes', '0001_initial'),
        ('persons', '0001_initial'),
        ('products', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('document_type', models.CharField(choices=[('receipt', 'Прихід'), ('expense', 'Витрата')], default='receipt', max_length=10, verbose_name='Тип документу')),
                ('hold', models.BooleanField(default=False, verbose_name='Проведено')),
                ('paid', models.BooleanField(default=False, verbose_name='Сплачено')),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_documents', to='cashes.cash', verbose_name='Каса')),
                ('price_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricename_documents', to='products.pricename', verbose_name='Тип ціни')),
                ('provider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='provider_documents', to='persons.provider', verbose_name='Постачальник')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_documents', to='stocks.stock', verbose_name='Склад')),
                ('valuta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='valute_documents', to='cashes.valuta', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документи',
                'ordering': ['provider_id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovementDocumentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кількість')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_in_stock_movement_document', to='products.productrefbook', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в документі переміщення',
                'verbose_name_plural': 'Товари в документі переміщення',
            },
        ),
        migrations.CreateModel(
            name='StockMovementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('stock_end', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stock_end_documents', to='stocks.stock', verbose_name='На склад')),
                ('stock_start', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='stock_start_documents', to='stocks.stock', verbose_name='Зі складу')),
            ],
            options={
                'verbose_name': 'Документ переміщення',
                'verbose_name_plural': 'Документи переміщення',
            },
        ),
        migrations.CreateModel(
            name='ProductInDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_document', to='documents.document', verbose_name='Документ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_in_products_in_document', to='products.productrefbook', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в документі',
                'verbose_name_plural': 'Товари в документі',
            },
        ),
        migrations.CreateModel(
            name='CashDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('cash_document_description', models.CharField(blank=True, default=None, max_length=50, verbose_name='Опис документа')),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_document_documents', to='cashes.cash', verbose_name='Каса')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_documents', to='documents.document', verbose_name='Номер документа')),
            ],
            options={
                'verbose_name': 'Документ каси',
                'verbose_name_plural': 'Документи каси',
                'ordering': ['-create_date', 'cash_id'],
            },
        ),
    ]
