# Generated by Django 4.2.3 on 2024-02-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-create_date'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документи'},
        ),
    ]
