# Generated by Django 4.2.2 on 2023-07-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('receipt', 'Прихід'), ('expense', 'Витрата')], default='receipt', max_length=10, verbose_name='Тип документу'),
        ),
    ]
