# Generated by Django 4.2.2 on 2023-06-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('client_name', models.CharField(default=None, max_length=30, verbose_name="Ім'я")),
                ('phone', models.CharField(default=None, max_length=30, verbose_name='Телефон')),
                ('birthday_date', models.DateField(default=None, verbose_name='Дата народження')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('first_name', models.CharField(default=None, max_length=30, verbose_name="Ім'я")),
                ('last_name', models.CharField(default=None, max_length=30, verbose_name='Прізвище')),
                ('contract', models.CharField(default=None, max_length=30, verbose_name='Номер контракту')),
                ('position', models.CharField(default=None, max_length=30, verbose_name='Посада')),
                ('phone', models.CharField(default=None, max_length=15, verbose_name='Телефон')),
                ('address', models.CharField(default=None, max_length=30, verbose_name='Адреса')),
                ('start_date', models.DateField(verbose_name='Дата прийняття')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата звільнення')),
            ],
            options={
                'verbose_name': 'Працівник',
                'verbose_name_plural': 'Працівники',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('manufacturer_name', models.CharField(default=None, max_length=30, verbose_name="Назва або Ім'я")),
                ('country', models.CharField(default=None, max_length=30, verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Виробник',
                'verbose_name_plural': 'Виробники',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('provider_name', models.CharField(default=None, max_length=30, verbose_name="Назва або Ім'я")),
                ('city', models.CharField(default=None, max_length=30, verbose_name='Місто')),
                ('address', models.CharField(default=None, max_length=30, verbose_name='Адреса')),
                ('phone', models.CharField(default=None, max_length=15, verbose_name='Телефон')),
                ('status', models.CharField(choices=[('individual', 'Фізична особа'), ('legal', 'Юридична особа')], default=None, max_length=15, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенти',
            },
        ),
    ]
