# Generated by Django 4.2.2 on 2023-06-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['birthday_date'], 'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['position'], 'verbose_name': 'Працівник', 'verbose_name_plural': 'Працівники'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['country'], 'verbose_name': 'Виробник', 'verbose_name_plural': 'Виробники'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['provider_name', 'city'], 'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенти'},
        ),
    ]
