# Generated by Django 4.2.2 on 2023-06-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_clients_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, default=' ', null=True, verbose_name='Дата звільнення'),
        ),
    ]
