# Generated by Django 4.2.2 on 2023-06-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_employee_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата звільнення'),
        ),
    ]
