# Generated by Django 4.2.2 on 2023-06-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_alter_employee_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(default=None, max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(default=None, max_length=50, verbose_name='Адреса'),
        ),
    ]
