# Generated by Django 4.2.2 on 2023-06-24 17:56

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_alter_clients_phone_alter_provider_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
