# Generated by Django 4.2.2 on 2023-06-24 18:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_alter_provider_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Некоректний номер'}, max_length=128, region='UA', verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Некоректний номер'}, max_length=128, region='UA', verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Некоректний номер'}, max_length=128, region='UA', verbose_name='Телефон'),
        ),
    ]
