# Generated by Django 4.2.2 on 2023-06-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_alter_clients_phone_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
    ]
