# Generated by Django 4.2.2 on 2023-06-24 21:45

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_rename_clients_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Країна'),
        ),
    ]
