# Generated by Django 4.2.2 on 2023-06-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_alter_manufacturer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(default=None, max_length=30, verbose_name='Країна'),
        ),
    ]
