# Generated by Django 4.2.2 on 2023-06-24 22:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_alter_manufacturer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=django_countries.fields.CountryField(default='Україна', max_length=30, verbose_name='Країна'),
        ),
    ]
