# Generated by Django 4.2.3 on 2023-07-11 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_products_in_document', to='documents.document', verbose_name='Документ')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_products_in_stock', to='stocks.stock', verbose_name='Склад')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
