# Generated by Django 4.2.3 on 2023-07-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('product_balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='balance_products_in_product_ref_book', to='products.productrefbook', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
