# Generated by Django 4.2.3 on 2023-07-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_balance', '0002_balanceproduct_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balanceproduct',
            options={'verbose_name': 'Залишок', 'verbose_name_plural': 'Залишки'},
        ),
        migrations.RemoveField(
            model_name='balanceproduct',
            name='sum',
        ),
    ]
