# Generated by Django 4.2.3 on 2023-07-11 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('product_balance', '0003_alter_balanceproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balanceproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='balanceproduct',
            name='product_in_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='balance_products_in_product_in_document', to='documents.productindocument', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
