# Generated by Django 4.2.2 on 2023-07-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Створено:')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Редаговано:')),
                ('stock_name', models.CharField(default=None, max_length=30, verbose_name='Назва')),
                ('stock_address', models.CharField(default=None, max_length=50, verbose_name='Адреса')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
                'ordering': ['stock_name'],
            },
        ),
    ]
