# Generated by Django 4.2.2 on 2023-06-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productprice_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.price', verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='unitOfMeasure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.unitofmeasure', verbose_name='Од. виміру'),
        ),
    ]
