# Generated by Django 4.2.2 on 2023-06-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productprice_price_alter_productprice_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='PriceName',
        ),
        migrations.RenameModel(
            old_name='ProductPrice',
            new_name='ProductPriceName',
        ),
    ]
