# Generated by Django 4.2.2 on 2023-06-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_price_pricename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricename',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.pricename', verbose_name='Тип ціни'),
        ),
    ]
