# Generated by Django 4.2.2 on 2023-06-27 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productprice_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productrefbook_products', to='products.productrefbook', verbose_name='Товар'),
        ),
    ]
