# Generated by Django 4.2.2 on 2023-06-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_alter_manufacturer_country'),
        ('products', '0005_alter_productrefbook_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrefbook',
            name='manufacturer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='manufacturer_products', to='persons.manufacturer', verbose_name='Виробник'),
        ),
    ]
